---
locale: es
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Sí, me encantó
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No, me aburrió
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Más o menos, hay cosas para mejorar
  checked: false
name: Dí que sí
