---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La primera en la que Nadia presentó la plataforma
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Cuando hablaron las chicas de Mumuki, y también estuvo Nadia
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Cuando Nadia nos mostró el examen
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Las otras en las que no estuvo Nadia
  checked: false
name: Mentiroso mentiroso
