---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
language: javascript
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: \s*pagaConTarjeta\s*\(\s*true\s*,\s*"débito"\s*,\s*32\s*\)\s*
name: Nuevo ejercicio
